main: com.lerdorf.fancy_arena.FancyArena
name: CarlsFancyArenas
author: carl_alex
version: 1.0
api-version: 1.13

commands:
   moditem:
      description: Modifies the attributes and metadata of the item in your hand
      usage: /moditem [options]
      permission: FancyArenas.moditem
   fancymob:
      description: For creating custom mobs
      usage: /fancymob [options]
      permission: FancyArenas.fancymob
   fancyitem:
      description: For managing custom items
      usage: /fancyitem [options]
      permission: FancyArenas.fancyitem
   fancyarena:
      description: For setting up custom arenas and dungeons
      usage: /fancyarena [options]
      permission: FancyArenas.fancyarena
   fa:
      description: For setting up custom arenas and dungeons
      usage: /fa [options]
      permission: FancyArenas.fancyarena
   shop:
      description: Shopping for the yeet squad
      usage: /shop
      permission: FancyArenas.shop
   cbscan:
      description: Scans for command blocks
      usage: /cbscan <radius>
      permission: FancyArenas.cbscan
   rm:
      description: Removes an entity
      usage: /rm <selector>
      permission: FancyArenas.rm